### PR TITLE
Ultra Hard: prevent using letter in a previously grey position

### PR DESCRIPTION
**Pull request by mcpower**
For example, with a target word of RALLY ([challenge link]), guessing ARRAY gives [elsewhere, elsewhere, absent, absent, correct].
This commit makes guessing SPRAY a violation, as we know that A cannot be in the first or fourth positions (or else one of them would be correct), and R cannot be in the second or third positions.

Before:
<details>
<summary>Image showing SPRAY guessed after ARRAY</summary>

</details>

After:
<details>
<summary>Image showing SPRAY cannot be guessed after ARRAY as "3rd letter can't be R"</summary>

</details>

[challenge link]: https://hellowordl.net/?challenge=cmFsbHk

### CODE REVIEW

**Comment by mcpower** [comment]
There's a similar check in the `if (clue === Clue.Elsewhere)` branch of the `violation` function. Should the two branches be merged like this?

```ts
if (difficulty === Difficulty.UltraHard && clue !== Clue.Correct && guess[i] === letter) {
  return nth + " letter can't be " + upper;
}
```

**Comment by lynn** [comment]
> Edit: We should probably do this if #55 is merged in. The `if (clue === Clue.Absent)` branch is deleted and a new `if (difficulty === Difficulty.UltraHard)` branch is added in that PR, so the above could nicely fit into the new Ultra Hard branch.

I merged #55, so feel free to make this change.

**Comment by mcpower** [comment]
Done in the merge commit. Feel free to [squash and merge](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#squash-and-merge-your-pull-request-commits) for a cleaner commit history.

**Comment by lynn** [comment]
Thanks!

**Pull request merged**
